### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by ibigfire** [enra4/discord-schedule-messages#4]
Hi, I'm so sorry for bugging you again, especially after all you've done.  I just can't seem to get it to work.

I got my token just fine, although it came with quotation marks around it so I tried both with the quotation marks and without.  I put in my token into the app.js file, I got the ID of a channel I wanted to send a message to, and a person I could use for testing DM messages, I saved the contacts of each just fine and the contact information is being saved to the channels.json file properly and everything.

But when it's supposed to send a message it just, well, never sends it.

So I have a couple theories.  Maybe I'm somehow inputting the token incorrectly, although I've tried the three different ways I can think of, or maybe it's somehow incompatible with Windows?  Or maybe some other problem I haven't thought of.

Should the token format be 
`const token = 'gyZHGkWoCCdgGHKET3RphptyCQOpJVIR7zvJ4UbZ7VdWHyjVXwHqJTXZi8K5' // insert token here`
or
`const token = '"gyZHGkWoCCdgGHKET3RphptyCQOpJVIR7zvJ4UbZ7VdWHyjVXwHqJTXZi8K5"' // insert token here`
or
`const token = "gyZHGkWoCCdgGHKET3RphptyCQOpJVIR7zvJ4UbZ7VdWHyjVXwHqJTXZi8K5" // insert token here`

That isn't my real token, of course, just a random string for this issue report.  And I assume it's the top format, but I've tested with all formats and none have fixed it.

And this is what I'm putting into the prompt:
https://i.imgur.com/gwYPozk.png

But doing so never sends any message to either Nadeko or the channel.

**Comment by enra4** [comment]
hello again and sorry for me not really caring about testing this app before making commits, being naive and thinking everythings fine.

i seem to stumble upon the same problem as you, although i have some different thoughts to why this is happening. i definently don't think there is a problem with you being on windows, and just to be clear, the first and the latter way you inserted the token should work.

from some testing it appears that the the client, which is dependent on the discord.io library, seems to never connect. i rolled back to [this version](https://github.com/enra4/discord-schedule-messages/blob/001fb31eec84ef118596833fb7b27cb3c481c03d/app.js) and encountered the same problem. 

did this app work before you made the suggestion to add timestamps and moment? if not, maybe theres an update to the discord api, and the discord.io library is just outdated. will definetely look for another library, but would be useful to know if the app worked before you made your first issue on this repo.

**Comment by enra4** [comment]
[eris](https://github.com/abalabahaha/eris) seem to work, although it would mean that you would have to specify if its a DM-channel or a regular channel when saving contacts/channels

it would still be nice to know if this app worked for you before i made the timestamp changes, before i possibly move on to use eris instead of discord.io

**Comment by ibigfire** [comment]
Heya,

Absolutely no apologies necessary for the bugs.  I'm just happy you're putting up with my pestering about it!

So, I actually never got to the point where it would have sent the message on the old version before the timestamp changes were implemented.  I set it up to send the message in 2 days, and then left it running.  But I made the suggestion about being able to set specific times and you implemented that update so darn impressively quick that it never actually got to that day for sending the message before I went in and updated to the new version.

But!  I just now went back and downloaded the old version at this commit: [6ab47b17e3612dd9883e704cdc441989df84884d](https://github.com/enra4/discord-schedule-messages/tree/6ab47b17e3612dd9883e704cdc441989df84884d) and tested it out, and no, it doesn't send messages for me with that version either.

**Comment by enra4** [comment]
ok well i pushed some changes now, https://github.com/enra4/discord-schedule-messages/commit/b3146a8770f81ef2da2e7578ee33705c51c38434. it works a bit differently now, so make sure to read the readme again. hopefully everything works now

**Comment by ibigfire** [comment]
Seems to be working great now when I used the seconds until sending a message format!  Yay!

But when I use the date format it doesn't seem to send.  Is this the correct format?
`send Nadeko 2018-07-12T05:07 test`

Also, I noticed you credited me in the readme.  That wasn't necessary, I haven't done much you've done all the hard work I've just been a nuisance pointing out bugs and asking for new features, haha, but I'm honoured.  Thank you.  ^_^

**Comment by enra4** [comment]
it seems like i wrote wrong in the readme.. it should work if you `send-date Nadeko 2018-07-12T05:07 test`. also i would like to point out that this schedules a message for 05:07 AM and **not** PM. 

also i want to point out that `send` is minutes until and not seconds until, but you probably just mistyped

fixed here https://github.com/enra4/discord-schedule-messages/commit/fe6ba5898312ace507054892b3885bddedbba9c4

**Comment by ibigfire** [comment]
Ah ha!  Yes, I mistyped, I meant minutes.  Okay, so, switching to `send-date` still didn't seem to be working.  But it accidentally worked once when I put in the wrong date.  So I was thinking, maybe, that it had to do with timezones or some such.  After some testing today something along those lines does seem to be the case.

When I put in `send-date IMnadeko 2018-07-12T09:00 9` it sent that message at 4:00pm PDT (my timezone).  And `send-date IMnadeko 2018-07-12T10:01 10` was successfully sent at 5:01pm PDT, and since I left it running while I slept it sent a bunch of messages and I confirmed that it does definitely work consistently, but seems to be set at an offset from my current time.

For reference, here are the commands I put in to the program, and the messages as they were sent in Discord:
https://i.imgur.com/w5orlLw.png
https://i.imgur.com/78ow0QP.png

If you wanted to leave it like this, you could, and just say that the send-date command is based around whatever timezone that is.  People can convert the offset themselves just fine I imagine.  But just figured I'd give you the results of my testing.

**Comment by enra4** [comment]
huh, i did try to adjust for timezone in the code, and it works for me. maybe `moment` adjusts for your timezone autimatically somehow but not mine?

if you would'nt mind, could you try replacing lines 116-118 in app.js and see if it works for you (or how it works):
```js
const scheduled = moment(input[2])
const offset = moment().utcOffset()
const delay = moment(scheduled).diff(moment().add(offset, 'minutes'))
```
with:
```js
const scheduled = moment(input[2])
const delay = moment(scheduled).diff(moment())
```

other than that, i don't know how to resolve this issue since it seems to behave differently for you than it does for me.

**Comment by ibigfire** [comment]
Made that change and it sends it at the time written in my own timezone.  `send-date IMnadeko 2018-07-13T03:55 0355test` sent the message at 03:55am for me.

Super duper weird why the offset is working differently for the two of us.

**Comment by enra4** [comment]
weird, thanks anyway.

updating the readme and opening a new issue
